# Generated by Django 5.0.4 on 2024-04-03 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'site_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Saveddata',
            fields=[
                ('saveid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('graph', models.BinaryField()),
                ('timeframe', models.CharField(max_length=3)),
                ('metric_type', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.PROTECT, to='SearchApp.siteuser')),
            ],
            options={
                'db_table': 'saveddata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('timeframe', models.CharField(max_length=3)),
                ('ticker', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('saveid', models.ForeignKey(blank=True, db_column='saveid', null=True, on_delete=django.db.models.deletion.PROTECT, to='SearchApp.saveddata')),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Majorholders',
            fields=[
                ('major_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('holder', models.CharField(blank=True, max_length=255, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('datereported', models.DateField(blank=True, null=True)),
                ('percentout', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SearchApp.stock')),
            ],
            options={
                'db_table': 'majorholders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institutionalholders',
            fields=[
                ('institutional_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('datereported', models.DateField(blank=True, null=True)),
                ('percentout', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SearchApp.stock')),
            ],
            options={
                'db_table': 'institutionalholders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('dividend_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('dividend', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SearchApp.stock')),
            ],
            options={
                'db_table': 'dividends',
                'managed': True,
            },
        ),
    ]
