# Generated by Django 5.0.4 on 2024-04-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0002_alter_dividends_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dividends',
            table='DIVIDENDS',
        ),
    ]
