# Generated by Django 5.0.4 on 2024-04-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0003_alter_dividends_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionalholders',
            old_name='datereported',
            new_name='date_reported',
        ),
        migrations.RenameField(
            model_name='institutionalholders',
            old_name='name',
            new_name='holder',
        ),
        migrations.RenameField(
            model_name='institutionalholders',
            old_name='percentout',
            new_name='percent_out',
        ),
        migrations.RenameField(
            model_name='majorholders',
            old_name='datereported',
            new_name='date_reported',
        ),
        migrations.RenameField(
            model_name='majorholders',
            old_name='percentout',
            new_name='percent_out',
        ),
        migrations.RenameField(
            model_name='saveddata',
            old_name='graph',
            new_name='diagram',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='description',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='close',
            new_name='record_close',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='record_date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='high',
            new_name='record_high',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='low',
            new_name='record_low',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='open',
            new_name='record_open',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='time',
            new_name='record_time',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='volume',
            new_name='record_volume',
        ),
        migrations.RemoveField(
            model_name='dividends',
            name='date',
        ),
        migrations.AddField(
            model_name='dividends',
            name='record_date',
            field=models.DateField(blank=True, db_column='RecordDate', null=True),
        ),
    ]
