# Generated by Django 5.0.4 on 2024-04-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0004_rename_datereported_institutionalholders_date_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalholders',
            name='date_reported',
            field=models.DateField(blank=True, db_column='DateReported', null=True),
        ),
        migrations.AlterField(
            model_name='institutionalholders',
            name='percent_out',
            field=models.FloatField(blank=True, db_column='PercentOut', null=True),
        ),
        migrations.AlterField(
            model_name='majorholders',
            name='date_reported',
            field=models.DateField(blank=True, db_column='DateReported', null=True),
        ),
        migrations.AlterField(
            model_name='majorholders',
            name='percent_out',
            field=models.FloatField(blank=True, db_column='PercentOut', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='information',
            field=models.TextField(blank=True, db_column='Information', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='record_close',
            field=models.FloatField(blank=True, db_column='RecordClose', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='record_date',
            field=models.DateField(db_column='RecordDate'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='record_high',
            field=models.FloatField(blank=True, db_column='RecordHigh', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='record_low',
            field=models.FloatField(blank=True, db_column='RecordLow', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='record_open',
            field=models.FloatField(blank=True, db_column='RecordOpen', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='record_time',
            field=models.CharField(blank=True, db_column='RecordTime', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='record_volume',
            field=models.BigIntegerField(blank=True, db_column='RecordVolume', null=True),
        ),
    ]
