# Generated by Django 5.0.4 on 2024-04-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0005_alter_institutionalholders_date_reported_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividends',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='institutionalholders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='majorholders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='saveddata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False},
        ),
    ]
