# Generated by Django 5.0.4 on 2024-04-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0006_alter_dividends_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dividends',
            table='dividends',
        ),
    ]
