# Generated by Django 5.0.4 on 2024-04-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0007_alter_dividends_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveddata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={},
        ),
    ]
